name: Build and check links in PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Use Node.js 17.8.x
        uses: actions/setup-node@main
        with:
          node-version: 17.8.x
      - name: Replace base url
        run: |
          # replace base url to localhost to support change of doc structure
          sed -i 's#https://devlake.apache.org#http://local.devlake.apache.org#g' docusaurus.config.js
      - name: Edit hosts
        run: |
          # why we need this:
          # lychee will ignore links to localhost, so we need to add a new domain to avoid this
          echo "127.0.0.1 local.devlake.apache.org" | sudo tee -a /etc/hosts
      - name: Build Docusaurus website
        run: |
          npm install
          npm run build
      - name: Install http-server
        run: |
          sudo npm install -g http-server
      - name: Install lychee
        env:
          LYCHEEVERSION: 0.12.0
        # due to the limitation of Apache, we can't use lycheeverse/lychee-action directly,
        # so we re-use some core code from it(install)
        run: |
          curl -sLO "https://github.com/lycheeverse/lychee/releases/download/v${{ env.LYCHEEVERSION }}/lychee-v${{ env.LYCHEEVERSION }}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf "lychee-v${{ env.LYCHEEVERSION }}-x86_64-unknown-linux-gnu.tar.gz"
          rm "lychee-v${{ env.LYCHEEVERSION }}-x86_64-unknown-linux-gnu.tar.gz"
          install -t "$HOME/.local/bin" -D lychee 
          rm lychee
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Link Checker
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          # to run a local server, so that lychee can check links on it rather than on devlake.apache.org
          sudo http-server ./build -s -p 80 -a 0.0.0.0 &
          # wait for http-server to start
          npm install wait-on
          npx wait-on http://local.devlake.apache.org -t 60000
          
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          # -E, --exclude-all-private    Exclude all private IPs from checking.
          # -i, --insecure               Proceed for server connections considered insecure (invalid TLS)
          # -n, --no-progress            Do not show progress bar.
          # -t, --timeout <timeout>      Website timeout in seconds from connect to response finished [default:20]
          # --max-concurrency <max-concurrency>    Maximum number of concurrent network requests [default: 128]
          # -a --accept <accept>                      Comma-separated list of accepted status codes for valid links
          # -m, --max-redirects <MAX_REDIRECTS>

          # 'build': the site directory to check
          # './*.md': all markdown files in the root directory

          lychee -E -i -n -t 45 --max-concurrency 64 -a 401,403 -m 10 -- 'build' '*.md'
